# Generated by Django 4.2.16 on 2025-06-30 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationPoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommandeLivreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('payee', models.BooleanField(default=False)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('mode_paiement', models.CharField(blank=True, choices=[('espece', 'Espèces'), ('mobile', 'Mobile Money'), ('virement', 'Virement')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntreeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fournisseur', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('actif', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Livreur',
                'verbose_name_plural': 'Livreurs',
            },
        ),
        migrations.CreateModel(
            name='Ouvrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('telephone', models.CharField(max_length=20, unique=True, verbose_name='Téléphone')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('remuneration', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mode_paiement', models.CharField(choices=[('jour', 'Jour'), ('semaine', 'Semaine'), ('mois', 'Mois')], max_length=10)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=6)),
                ('prix_livreur', models.DecimalField(decimal_places=2, max_digits=6)),
                ('actif', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaiementSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('mode_paiement', models.CharField(choices=[('espece', 'Espèces'), ('mobile', 'Mobile Money'), ('virement', 'Virement')], max_length=10)),
                ('ouvrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.ouvrier')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.poste')),
            ],
            options={
                'verbose_name': 'Paiement de salaire',
                'verbose_name_plural': 'Paiements de salaires',
            },
        ),
        migrations.AddConstraint(
            model_name='ouvrier',
            constraint=models.UniqueConstraint(condition=models.Q(('nom__isnull', False)), fields=('nom',), name='unique_nom_ouvrier', violation_error_message='Un ouvrier avec ce nom existe déjà'),
        ),
        migrations.AddConstraint(
            model_name='ouvrier',
            constraint=models.UniqueConstraint(fields=('telephone',), name='unique_telephone_ouvrier', violation_error_message='Un ouvrier avec ce numéro existe déjà'),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.produit'),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='gestion.vente'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='gestion.commandelivreur'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.produit'),
        ),
        migrations.AddField(
            model_name='entreestock',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.produit'),
        ),
        migrations.AddField(
            model_name='commandelivreur',
            name='livreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.livreur'),
        ),
        migrations.AddField(
            model_name='affectationposte',
            name='ouvrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.ouvrier'),
        ),
        migrations.AddField(
            model_name='affectationposte',
            name='poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.poste'),
        ),
    ]
