# Generated by Django 4.2.16 on 2025-07-04 15:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('present', models.BooleanField(default=False)),
                ('heures_travaillees', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ouvrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.ouvrier')),
                ('poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.poste')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-date', 'ouvrier__nom'],
                'unique_together': {('ouvrier', 'date')},
            },
        ),
    ]
