# Generated by Django 4.2.16 on 2025-07-04 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_presence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='ouvrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='gestion.ouvrier'),
        ),
    ]
